#!/usr/bin/env bash
# Boot the game.  ./tools/play.sh
# Boot the reader. ./tools/switch.sh reader   (or hold POWER ~1.5s in the game)
#
# WHY USB IS NEEDED FOR THIS DIRECTION
# Booting app1 means writing an otadata record that selects slot 1. Going the
# other way needs no host - the game does it itself with esp_ota_set_boot_partition
# when you hold POWER. But CrossPoint has no code to select slot 1, so the trip
# INTO the game has to be made by something that can write flash, which is this
# script over the USB cable. That asymmetry is a property of the firmware
# split, not of this script.
#
# The record itself is generated by mkotadata.py, which derives the CRC scheme
# from the device's own otadata copies and refuses to emit bytes unless it can
# reproduce them. If anything is ever wrong the bootloader ignores the bad copy
# and boots the other one - you land in CrossPoint, never in a brick.
set -uo pipefail
cd "$(dirname "$0")/.."

E="${ESPTOOL:-$HOME/XteinkX3-backup/tools/esptool-env/bin/esptool}"
PORT="${PORT:-/dev/cu.usbmodem8401}"

[ -x "$E" ] || { echo "esptool not at $E"; exit 1; }
[ -e "$PORT" ] || { echo "no device on $PORT  (ls /dev/cu.usb*)"; exit 1; }

T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT

rd() {  # rd <addr> <len> <out> - one invocation only.
  # The C3's port re-enumerates when the ROM bootloader takes over from the
  # running firmware, so a second esptool call often cannot reopen the node.
  # Reading the whole 8 KB otadata partition in a single call and slicing it
  # sidesteps that entirely.
  local i
  for i in 1 2; do
    "$E" --chip esp32c3 --port "$PORT" --before default-reset --after no-reset \
         read-flash "$1" "$2" "$3" >/dev/null 2>&1
    [ -s "$3" ] && return 0
    sleep 1
  done
  echo "  failed to read $1"
  return 1
}

echo "reading otadata (one 8 KB read, sliced locally)..."
rd 0xE000 8192 "$T/ota.bin" || exit 1
python3 - "$T" <<'PY'
import sys, os
T = sys.argv[1]
d = open(os.path.join(T, "ota.bin"), "rb").read()
if len(d) < 4128:
    sys.exit(f"otadata read too short: {len(d)} bytes")
open(os.path.join(T, "c0.bin"), "wb").write(d[0x000:0x020])   # copy #0 -> slot 0
open(os.path.join(T, "c1.bin"), "wb").write(d[0x1000:0x1020]) # copy #1 -> slot 1
print(f"  copy#0 seq={int.from_bytes(d[0:4],'little')}  "
      f"copy#1 seq={int.from_bytes(d[0x1000:0x1004],'little')}")
PY
[ -s "$T/c0.bin" ] && [ -s "$T/c1.bin" ] || { echo "slice failed"; exit 1; }

python3 tools/mkotadata.py --slot 1 --copy0 "$T/c0.bin" --copy1 "$T/c1.bin" \
       --out "$T/app1.bin" || { echo "selector generation refused - nothing written"; exit 1; }

echo
echo "writing slot-1 selector and rebooting into Blackjack..."
# The port can still be settling after the read above, and the earlier version
# of this script printed "done" unconditionally even when this write failed.
wrote=0
for i in 1 2 3 4 5; do
  out=$("$E" --chip esp32c3 --port "$PORT" --before default-reset --after hard-reset \
        write-flash 0xF000 "$T/app1.bin" 2>&1)
  echo "$out" | grep -E "Wrote|Hash" | sed 's/^/  /'
  if echo "$out" | grep -q "Hash of data verified"; then wrote=1; break; fi
  echo "  write attempt $i failed: $(echo "$out" | grep -oE 'busy|doesn.t exist|fatal[^ ]*' | head -1)"
  sleep 3
done

if [ "$wrote" != "1" ]; then
  echo
  echo "FAILED to write the selector - nothing changed, device still on its current"
  echo "firmware. Unplug/replug USB and re-run. Still readable, not bricked."
  exit 1
fi

echo
echo "done - the panel should refresh to the ARCADE menu in a second or two."
echo "back to the reader: hold POWER ~1.5s, or ./tools/switch.sh reader"
